name: Release draft

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ReleaseDraft:
    strategy:
      matrix:
        include:
          - name: mac-silicon
            os: macos-latest
            goos: darwin
            goarch: arm64
            binary: aicommits-mac-silicon
          - name: raspberry-pi
            os: ubuntu-latest
            goos: linux
            goarch: arm64
            binary: aicommits-raspberry-pi

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w" -trimpath -o ${{ matrix.binary }} ./cmd

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: draft
          draft: true
          name: Draft
          files: |
            ${{ matrix.binary }}